### ISSUE TITLE
Better support for mobile devices

### ISSUE THREAD

**Issue by Forza-tng** [darkling/btrfs-usage#1]
Hi!

It would be nice if the layout could be made a little more responsive. 

Mainly I think it is the length of the usage bars that should be using percentages instead of fixed pixel widths.

https://carfax.org.uk/btrfs-usage/index.html

I did some testing in the browser dev-tools with percentages. I set the bigest device to 100% and then the others as relative size. This makes work much nicer on mobile phones. :)

![image](https://user-images.githubusercontent.com/68693597/130245538-e18e586b-5d65-4da6-9352-a26259470288.png)

**Comment by darkling** [comment]
I tried setting the device widths to fractions of 100%, and I got nothing. They collapse into 0px.
What's the exact CSS/tyling you're using to get that effect, because I can't see how to make it work. (I did warn you that CSS wasn't my thing...)

**Comment by darkling** [comment]
Ah, never mind, I think I've got something. It's still not perfect (the overall bar length changes slightly as you change parameters), but it's doing a reasonable job now.

**Comment by darkling** [comment]
Should be done now with #2
