### ISSUE TITLE
i think bug using 2Tb and a 6TB drive stripped 

### ISSUE THREAD

**Issue by comet424** [darkling/btrfs-usage#5]
not sure if its a bug but kinda seems it  
first i have a 1TB and 2TB  drive  i was looking at stripping  but i guess you loose 1TB data
as it 2TB usable  and 1 TB unusable

but if i was to mix  a 2TB  and a 6TB  and stripe that data  to get 8TB
it says  i have 4TB thats useable and 4TB that unusable 

does that mean id have 0TB useable ?
as i thought id get 8TB useable 

or is it 
2TB (2TB drive) +  2TB (6TB drive) = 4 usuable   and  4TB left on the 6TB is unusable  

is that how that works?  if so then not a bug but maybe a better break down when showing useable/unusable as it took me a bit to figure it out

if if you could add color on the bars     to show   like  blue section of the bar is unusable    and green part of the bar is useable

**Comment by darkling** [comment]
No, that's correct. RAID-0 striping requires at least two devices, so once it's filled the small drive, and the corresponding 2 TB of the larger drive, it can't allocate any more space. At that point, it's striped over 2TB of each of two drives, for a total of 4 TB, and 4 TB on the large drive unusable.

If you want to use all the space on two unequal drives, use single mode, without the striping.

**Comment by comet424** [comment]
ah  ok  i got your link from  unraid forums  as i been having issues with Btfrs   and i having   800gb used on a single 1TB  
but when  i added a 2TB  to the pool   ichanged it to 1.5Tb  file system...  it too the 800GB used to  400GB used  and a 1TB usuable of 1.5 of 3TB     in a raid 1..  so its been confusing

it be nice also on your page  it help..  color code  the bar

so you have green  so  that be useable.. and then change the rest of the bar   to say Red  or blue  and corispondes to unusable

so like
green bar = useable
red bar = unusable 

or u have the white bar..  say   white bar = unusable 
that would really help


but it is confusing  as i changed my 2 drives in unraid from i guess Raid 1 (best performance)  to Raid 0    and it shows 2.4TB drive  from  1TB and a 2TB

i guessing best practice  is not mix an match  get all the same drive..

it basiclly works like parity drive i guess the striping  but in parity you want the biggest drive

**Comment by comet424** [comment]
so best practice is stripe or mirror use same size drives    and mixed drives  just as a single drive  then there is no headaches

**Comment by darkling** [comment]
Best practice would be striping (or parity) with the _n_ largest disks being the same size (where _n_ is the minimum number of disks for the RAID level).

For RAID-1, it can cope with far more unequal devices -- the general rule there is that the largest device should be smaller than the sum of the rest of the devices.

**Comment by darkling** [comment]
Come and join us on [IRC](https://web.libera.chat), #btrfs if you want to discuss this further.

**Comment by comet424** [comment]
havent used IRC in forever..  use to use it in 1991    is it under efnet server?

**Comment by darkling** [comment]
Libera.chat (see the link above)
