### ISSUE TITLE
Account for degenerate RAID0

### ISSUE THREAD

**Issue by Atemu** [darkling/btrfs-usage#6]
With 5.15, btrfs introduced [degenerate RAID0/RAID10](https://lore.kernel.org/linux-btrfs/20210722192955.18709-1-dsterba@suse.com/) which allows RAID0 to span a single disk (stripe width = 1).

Previously unusable space now gets allocated in degenerate RAID0 mode, allowing striped modes to fully utilise the space their non-striped counterpart could.

**Comment by Atemu** [comment]
A workaround on the current website is to first select your block group mode and then reduce min data stripes from 2 to 1.

**Comment by darkling** [comment]
I've added a checkbox for the kernel version, which switches the parameters of the RAID-0 and -10 presets to change the min data stripes.
